name: new_project

packages:
  - .
  - example
  - apps/*
  - packages/*
  - packages/*/example

scripts:
  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  analyze:
    exec: dart analyze .
  fix:
    run: dart fix --apply .
    exec:
      concurrency: 1
  sort:
    exec: dart pub global run import_sorter:main --no-comments
  precommit: melos fix && melos format && melos sort
  test:
    run: flutter test --no-pub --coverage
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
