name: project_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace: []

dependencies:
  path: ^1.9.1
  dotenv: ^4.2.0
  logger: ^2.7.0
  args: ^2.7.0

dev_dependencies:
  melos: ^8.3.0
  lints: ^6.1.0

melos:
  scripts:
    outdated:
      exec: dart pub outdated
    upgrade:
      exec: dart pub upgrade
    gen:
      exec: dart run build_runner build --delete-conflicting-outputs
      packageFilters:
        dependsOn: build_runner
    analyze:
      exec: dart analyze .
    fix:
      exec:
        command: dart fix --apply .
        concurrency: 1
    sort:
      exec: dart pub global run import_sorter --no-comments
    precommit: melos fix && melos format && melos sort
    test:
      exec:
        command: flutter test --no-pub --coverage
        concurrency: 1
      packageFilters:
        dirExists: test
